In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
dataset=pd.read_csv('comprehensive_mutual_funds_data_1.csv')
dataset['sortino'].replace('-', np.nan, inplace=True)
median=dataset['sortino'].median()
dataset['sortino'].fillna(median, inplace=True)
dataset['alpha'].replace('-', np.nan, inplace=True)
median1=dataset['alpha'].median()
dataset['alpha'].fillna(median1, inplace=True)
dataset['sd'].replace('-', np.nan, inplace=True)
median2=dataset['sd'].median()
dataset['sd'].fillna(median2, inplace=True)
dataset['beta'].replace('-', np.nan, inplace=True)
median3=dataset['beta'].median()
dataset['beta'].fillna(median3, inplace=True)
dataset['sharpe'].replace('-', np.nan, inplace=True)
median4=dataset['sharpe'].median()
dataset['sharpe'].fillna(median4, inplace=True)

In [3]:
encode={'Debt':0, 'Equity':1, 'Hybrid':2, 'Solution Oriented':3, 'Other':4}
dataset['category']=dataset['category'].map(encode)

In [4]:
dataset.to_csv('comprehensive_mutual_funds_data_1.csv')

In [5]:
dataset['sortino']=dataset['sortino'].astype(float)
dataset['alpha']=dataset['alpha'].astype(float)
dataset['sd']=dataset['sd'].astype(float)
dataset['beta']=dataset['beta'].astype(float)
dataset['sharpe']=dataset['sharpe'].astype(float)

In [6]:
median5 = dataset['returns_3yr'].median()
dataset['returns_3yr'].fillna(median5, inplace=True)
median6 = dataset['returns_5yr'].median()
dataset['returns_5yr'].fillna(median6, inplace=True)

In [7]:
dataset.to_csv('comprehensive_mutual_funds_data_1.csv')

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    float64
 8   alpha          814 non-null    float64
 9   sd             814 non-null    float64
 10  beta           814 non-null    float64
 11  sharpe         814 non-null    float64
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    int64
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    814 non-null    float64
 19  returns_5yr    814 non-null    float64
dtypes: float64(10), int64(6), object(4)
memory usage: 127.3+ KB

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [11]:
X=dataset.iloc[:,7:13].values
y=dataset.iloc[:,-2:-1].values

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
lin_reg=LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred=lin_reg.predict(X_test)

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [15]:
mae = mean_absolute_error(y_test, y_pred)
print('Mean absolute error for linear regression : ',mae)
mse = mean_squared_error(y_test, y_pred)
print('Mean squared error for linear regression : ',mse)
rmse = np.sqrt(mse)
print('Root mean squared error for linear regression : ',rmse)
r2 = r2_score(y_test, y_pred)
print('r2 score for linear regression : ',r2)

Mean absolute error for linear regression :  2.829626851209125
Mean squared error for linear regression :  21.15834722795217
Root mean squared error for linear regression :  4.599820347356206
r2 score for linear regression :  0.8472216135794322

In [16]:
from sklearn.preprocessing import PolynomialFeatures

In [17]:
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly_features.fit_transform(X_train)
X_test_poly = poly_features.fit_transform(X_test)
lin_reg.fit(X_train_poly, y_train)
y_pred_poly = lin_reg.predict(X_test_poly)

In [18]:
mae_poly = mean_absolute_error(y_test, y_pred_poly)
print('Mean absoulte error for polynomial regression : ',mae_poly)
mse_poly = mean_squared_error(y_test, y_pred_poly)
print('Mean squared error for polynomial regression : ',mse_poly)
rmse_poly = np.sqrt(mse_poly)
print('Root mean squared error for polynomial regression : ',rmse_poly)
r2_poly = r2_score(y_test, y_pred_poly)
print('r2 score for polynomial regression : ',r2_poly)

Mean absoulte error for polynomial regression :  1.4967380781903257
Mean squared error for polynomial regression :  14.44733158160685
Root mean squared error for polynomial regression :  3.80096455937264
r2 score for polynomial regression :  0.8956799421362727

In [19]:
from sklearn.linear_model import Ridge, Lasso

In [20]:
lasso_model = Lasso(alpha=0.85)
lasso_model.fit(X_train, y_train)
y_pred_lasso = lasso_model.predict(X_test)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
print('Mean squared error for lasso regression : ',mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)
print('r2 score for lasso regression : ',r2_lasso)

Mean squared error for lasso regression :  20.778704454005975
r2 score for lasso regression :  0.8499629056943051

In [21]:
ridge_model = Ridge(alpha=1, solver='cholesky')
ridge_model.fit(X_train, y_train)
y_pred_ridge = ridge_model.predict(X_test)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
print('Mean square error for ridge regression : ',mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)
print('r2 score for ridge regression : ',r2_ridge)

Mean square error for ridge regression :  21.132821082766593
r2 score for ridge regression :  0.8474059305882691

In [22]:
from sklearn.linear_model import ElasticNet
e_model = ElasticNet(alpha=0.1, l1_ratio=0.5)
e_model.fit(X_train, y_train)
y_pred_e = e_model.predict(X_test)
mse_e=mean_squared_error(y_test, y_pred_e)
print('Mean squared error for elastic net : ',mse_e)
r2_e = r2_score(y_test, y_pred_e)
print('r2 score for elastic net : ',r2_e)

Mean squared error for elastic net :  20.73455928283091
r2 score for elastic net :  0.8502816653756604

In [23]:
from sklearn.linear_model import SGDRegressor

In [24]:
sgd_model = SGDRegressor()
sgd_model.fit(X_train, y_train.ravel())
y_pred_sgd = sgd_model.predict(X_test)
mse_sgd = mean_squared_error(y_test, y_pred_sgd)
print('Mean squared error fo SGD : ',mse_sgd)
r2_sgd = r2_score(y_test, y_pred_sgd)
print('r2 score for SGD : ',r2_sgd)

Mean squared error fo SGD :  24.04452908667172
r2 score for SGD :  0.8263813181375956

In [25]:
sgd_model_mini_batch = SGDRegressor(loss='squared_error', penalty='l2', alpha=0.01, learning_rate='constant', eta0=0.01, max_iter=1000, shuffle=True, random_state=42)
sgd_model_mini_batch.fit(X_train, y_train.ravel())
y_pred_mini = sgd_model_mini_batch.predict(X_test)
mse_mini = mean_squared_error(y_test, y_pred_mini)
print('Mean squared error fo mini batch : ',mse_mini)
r2_mini = r2_score(y_test, y_pred_mini)
print('r2 score for mini : ',r2_mini)

Mean squared error fo mini batch :  9.80050872279465e+23
r2 score for mini :  -7.076667627380574e+21

In [26]:
sgd_model_poly = SGDRegressor()
sgd_model_poly.fit(X_train_poly, y_train.ravel())
y_pred_sgd_poly = sgd_model_poly.predict(X_test_poly)
mse_sgd_poly = mean_squared_error(y_test, y_pred_sgd_poly)
print('Mean squared error fo SGD for polynomial : ',mse_sgd_poly)
r2_sgd_poly = r2_score(y_test, y_pred_sgd_poly)
print('r2 score for SGD for polynomial : ',r2_sgd_poly)

Mean squared error fo SGD for polynomial :  4.778592347673578e+27
r2 score for SGD for polynomial :  -3.4504851459983446e+25

In [27]:
y_pred_poly

array([[ 8.35746272],
       [ 5.80368272],
       [ 6.89391638],
       [44.48115212],
       [ 5.16817087],
       [25.47776616],
       [36.21886301],
       [35.44482762],
       [27.76230333],
       [18.91311155],
       [11.47930569],
       [16.01385118],
       [ 6.30169683],
       [28.26340292],
       [ 6.24034001],
       [20.13947576],
       [40.9677027 ],
       [ 7.20196709],
       [32.64159028],
       [22.02334121],
       [ 5.28725822],
       [26.68098586],
       [57.39160377],
       [24.68377911],
       [31.65976703],
       [22.28328695],
       [ 6.39623859],
       [32.39029071],
       [ 5.08448063],
       [ 7.11427967],
       [23.93876944],
       [20.75172341],
       [35.91635134],
       [35.64636852],
       [32.02567448],
       [17.76270423],
       [20.88134854],
       [31.9566512 ],
       [36.37783035],
       [34.73144685],
       [ 5.93958917],
       [17.46401014],
       [22.59428079],
       [35.97463589],
       [ 6.01383134],
       [ 4.89107511],
       [26.21040077],
       [17.92894915],
       [18.08159555],
       [ 7.59103006],
       [24.44829121],
       [18.5725963 ],
       [ 4.77558855],
       [ 9.98758928],
       [ 7.10070593],
       [ 4.01338545],
       [14.74405695],
       [ 4.52549994],
       [ 5.64023651],
       [11.53678355],
       [20.8236636 ],
       [26.82909878],
       [ 4.44539298],
       [22.17780781],
       [ 5.44703125],
       [10.11038174],
       [ 6.95578545],
       [ 8.06823974],
       [ 4.54163142],
       [21.86019743],
       [14.37448982],
       [18.08159555],
       [ 4.80522594],
       [11.97731483],
       [22.07974016],
       [ 4.70753403],
       [ 5.51504799],
       [ 6.4526376 ],
       [ 6.47822379],
       [23.39507812],
       [31.59448782],
       [ 6.81021434],
       [17.58304131],
       [24.52370306],
       [15.5636369 ],
       [ 5.06117415],
       [19.78842795],
       [36.94112473],
       [34.40555889],
       [36.41786817],
       [32.34359817],
       [ 5.23841289],
       [ 5.81592674],
       [34.88375654],
       [ 4.52482888],
       [29.51236402],
       [13.74103206],
       [ 4.85548281],
       [10.60832802],
       [ 4.04465072],
       [ 5.5927634 ],
       [20.15987905],
       [26.32028177],
       [25.32955984],
       [21.79618321],
       [18.5725963 ],
       [10.99015202],
       [29.3569141 ],
       [13.24344887],
       [29.60600228],
       [ 6.14022446],
       [18.63678963],
       [ 8.52139155],
       [32.10058726],
       [32.4233158 ],
       [ 5.40624036],
       [13.60292043],
       [39.90263818],
       [ 6.45692032],
       [22.87868278],
       [14.30967643],
       [ 5.08524753],
       [25.22373043],
       [26.21040077],
       [20.88334483],
       [12.09087821],
       [ 6.41679412],
       [17.87188198],
       [31.74252768],
       [18.05996308],
       [31.19428898],
       [32.81826868],
       [32.97773899],
       [ 5.83895618],
       [ 5.55814799],
       [17.27724964],
       [34.6891537 ],
       [17.15022058],
       [28.98302875],
       [32.26530944],
       [ 8.49080579],
       [25.47631607],
       [ 9.84135018],
       [ 5.15454063],
       [46.48457517],
       [21.56645815],
       [26.6025334 ],
       [37.6205175 ],
       [22.63271344],
       [ 6.47014338],
       [ 5.69799462],
       [33.05539893],
       [25.29220525],
       [18.54662081],
       [27.91494477],
       [28.81812722],
       [26.47688866],
       [24.21272891],
       [25.88111367],
       [28.37130128],
       [ 5.14276712],
       [20.2789329 ],
       [36.59991304],
       [27.04190105],
       [ 6.28698281],
       [ 5.49375088],
       [ 5.11919914],
       [22.36875314],
       [36.52093944],
       [ 6.63689834],
       [21.08301374],
       [ 6.70207801],
       [29.60567483],
       [ 6.35733592],
       [23.75162865],
       [24.36641452],
       [28.4747448 ],
       [23.42474608],
       [ 5.11525732],
       [ 5.64677631],
       [ 6.78942665],
       [ 6.85490605],
       [36.29752626],
       [36.6344811 ],
       [22.53362889],
       [25.11392215],
       [25.16175092],
       [36.84323654],
       [ 5.13441502],
       [18.45750833],
       [ 5.90295239],
       [24.78494377],
       [41.97323757],
       [ 9.12456387],
       [ 6.28171513],
       [ 4.25901322],
       [ 6.07160542],
       [23.95935532],
       [30.46582689],
       [28.30139756],
       [27.14981262],
       [25.66612713],
       [20.58058193],
       [19.34412137],
       [25.84398371],
       [43.76310294],
       [26.61184469],
       [15.57548997],
       [28.67860102],
       [27.83240096],
       [ 6.07214031],
       [24.62395194],
       [25.74992645],
       [19.46437066],
       [12.41003162],
       [41.54304242],
       [ 5.76582839],
       [20.36131002],
       [25.14841463],
       [31.83577261],
       [34.91405503],
       [18.5725963 ],
       [ 4.82056394],
       [ 8.60267737],
       [26.23956905],
       [ 4.55409879],
       [ 6.91888977],
       [ 8.63073525],
       [ 7.01483039],
       [ 4.99356629],
       [23.69288449],
       [ 6.80514209],
       [ 4.60283645],
       [24.01436201],
       [23.63675451],
       [ 5.05831177],
       [23.73555835],
       [ 6.55943091],
       [ 5.33693658],
       [ 5.31127866],
       [31.69072205],
       [35.49028687],
       [30.28604938],
       [ 8.241774  ],
       [41.51339352]])

In [28]:
dataset1 = pd.read_csv('Predict.csv')

In [30]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    15 non-null     object
 1   min_sip        15 non-null     int64
 2   min_lumpsum    15 non-null     int64
 3   expense_ratio  15 non-null     float64
 4   fund_size      15 non-null     int64
 5   fund_age_yr    15 non-null     int64
 6   fund_manager   15 non-null     object
 7   sortino        15 non-null     float64
 8   alpha          15 non-null     float64
 9   sd             15 non-null     float64
 10  beta           15 non-null     float64
 11  sharpe         15 non-null     float64
 12  risk_level     15 non-null     int64
 13  amc_name       15 non-null     object
 14  rating         15 non-null     int64
 15  category       15 non-null     int64
 16  sub_category   15 non-null     object
 17  returns        0 non-null      float64
dtypes: float64(7), int64(7), object(4)
memory usage: 2.2+ KB

In [31]:
X1=dataset1.iloc[:,7:13].values
X1_transform = poly_features.fit_transform(X1)
y1_pred=lin_reg.predict(X1_transform)
y1_pred

array([[21.67820574],
       [15.5636369 ],
       [ 7.96744977],
       [31.83577261],
       [21.6825534 ],
       [24.16973428],
       [19.49350696],
       [ 5.4789167 ],
       [ 8.35746272],
       [ 5.24742241],
       [24.36641452],
       [23.420427  ],
       [14.19250663],
       [23.69288449],
       [17.55023333]])

In [32]:
dataset1['returns']=y1_pred

In [33]:
dataset1.head()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns
0,Canara Robeco Equity Hybrid Fund,1000,5000,0.63,8235,10,Shridatta Bhandwaldar,3.25,1.49,11.27,0.78,1.40,6,Canara Robeco Mutual Fund,4,2,Aggressive Hybrid Mutual Funds,21.678206
1,AXIS Retirement Savings Fund,1000,5000,0.65,633,3,Jinesh Gopani,1.56,-4.49,13.03,0.78,0.76,6,Axis Mutual Fund,1,3,Retirement Funds,15.563637
2,AXIS Credit Risk Fund,1000,5000,0.81,620,9,Devang Shah,1.97,3.22,1.62,0.26,1.77,4,Axis Mutual Fund,4,0,Credit Risk Funds,7.967450
3,DSP Nifty 50 Equal Weight Index Fund,500,500,0.40,498,5,Anil Ghelani,3.22,3.52,17.40,1.01,1.51,6,DSP Mutual Fund,3,4,Index Funds,31.835773
4,DSP Equity & Bond Fund,500,500,0.78,7358,10,Atul Bhole,2.70,0.51,12.70,0.83,1.25,6,DSP Mutual Fund,3,2,Aggressive Hybrid Mutual Funds,21.682553

In [36]:
dataset1.to_csv('Predict.csv')

In [37]:
sorted_dataset1 = dataset1.sort_values(by='returns', ascending=False)
sorted_dataset1.head()

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns
3,DSP Nifty 50 Equal Weight Index Fund,500,500,0.40,498,5,Anil Ghelani,3.22,3.52,17.40,1.01,1.51,6,DSP Mutual Fund,3,4,Index Funds,31.835773
10,HSBC Tax Saver Equity Fund,500,5000,1.30,175,10,Gautam Bhupal,3.05,-1.65,16.52,0.96,1.26,6,HSBC Mutual Fund,2,1,ELSS Mutual Funds,24.366415
5,Edelweiss Recently Listed IPO Fund,500,5000,0.61,859,5,Bhavesh Jain,1.63,0.04,17.77,0.83,1.09,6,Edelweiss Mutual Fund,0,1,Sectoral / Thematic Mutual Funds,24.169734
13,LIC MF S&P BSE Sensex Index Fund,1000,5000,0.38,68,10,Jaiprakash Toshniwal,3.40,-1.81,16.89,1.00,1.23,6,LIC Mutual Fund,3,4,Index Funds,23.692884
11,ICICI Pru Retirement Fund,100,5000,1.22,209,4,Lalit Kumar,2.78,2.63,11.88,0.78,1.44,6,ICICI Prudential Mutual Fund,5,3,Retirement Funds,23.420427